### ISSUE TITLE
JsonLDのバージョンが古いようで、エラーが出ました。

### ISSUE THREAD

**Issue by chiemi627** [uedayou/simplelodi#1]
ページを開こうとしたら以下のようなエラーが出ました。

Fatal error: Cannot use stdClass as Object because 'Object' is a special class name in /Users/chiemi/tmp/simplelodi/lib/JsonLD/Value.php on line 12

**Comment by chiemi627** [comment]
すみません、自己解決しました。
v2.0.0-devで実行したら問題なく動作いたしました。どうもありがとうございました！

**Comment by uedayou** [comment]
@chiemi627 
お知らせありがとうございました。
現在の master のコードは PHP 5.6 で動作を確認していました。
v2.0.0-dev は PHP7系で動作確認しました。

現在以下のサイトで、PHP7.3上でv2.0.0-dev のコードを運用しています。今のところ異常はありませんので利用していただいて問題はないかと思います。

鉄道駅LOD
https://uedayou.net/jrslod/

JSON-LD
https://uedayou.net/jrslod/東海旅客鉄道/東海道新幹線/東京.jsonld

今年中に v2.0.0-dev を master ブランチにマージしたいと思います。
引き続きどうぞよろしくお願いします。
